image:
  file: .gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when workspace gets loaded all docker images are ready
tasks:
  - prebuild: sudo docker-up &
  - prebuild: |
      # Wait for docker to come up before doing gitpod setup (gitpod-setup requires docker)
      while ! docker ps 2>/dev/null; do
        sleep 1
      done
      docker pull alpine:3.13.3
      docker run hello-world
      docker pull wordpress
      docker images
      docker images > file-created-during-prebuild.txt
