image:
  file: .gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when workspace gets loaded all docker images are ready
tasks:
  - prebuild: sudo docker-up &
  - prebuild: |
      # Wait for docker to come up before doing gitpod setup (gitpod-setup requires docker)
      while ! docker ps 2>/dev/null; do
        sleep 1
      done
      docker pull alpine:3.13.3
      docker run hello-world
      docker pull drud/ddev-webserver:v1.16.7
      docker pull drud/ddev-dbserver-mariadb-10.3:v1.16.0
      docker pull drud/ddev-ssh-agent:v1.16.0
      docker pull drud/ddev-router:v1.16.2
      docker images
      docker images > file-created-during-prebuild.txt
